# Exported from Render on 2025-10-25T18:48:44Z
version: "1"
services:
- type: web
  name: QuickShare
  runtime: python
  repo: https://github.com/Alan-88/QuickShare
  plan: free
  envVars:
  - key: PYTHON_VERSION
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: commit
  rootDir: backend
